;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
;; Don't edit this file, this is generated by config.org

(setq doom-theme 'doom-one)

(setq display-line-numbers-type `relative)

(use-package evil-owl
  :diminish ""
  :config
  (setq evil-owl-idle-delay 0.3)
  (setq evil-owl-max-string-length 500)
  (add-to-list 'display-buffer-alist
               '("*evil-owl*"
                 (display-buffer-in-side-window)
                 (side . bottom)
                 (window-height . 20)))
  (evil-owl-mode))

(global-prettify-symbols-mode)

(setq which-key-idle-delay 0.2)
(setq which-key-idle-secondary-delay 0.1)

(after! org
  (global-org-modern-mode))

(setq org-hide-emphasis-markers t)  ;; hides *bold* / /italic/ markers

(setq org-directory "~/org/")

(remove-hook 'tuareg-mode-local-vars-hook #'opam-switch-mode)

(use-package ocaml-eglot
  :ensure t
  :after tuareg
  :hook
  (tuareg-mode . ocaml-eglot)
  (ocaml-eglot . eglot-ensure)
  (ocaml-eglot . (lambda () (add-hook #'before-save-hook #'eglot-format nil t))))

(after! eglot
  (add-to-list 'eglot-server-programs
               '(tuareg-mode . ("ocamllsp")))
  (setq-default eglot-workspace-configuration
                '(:ocamllsp (:codelens t :inlayHints (:hintPatternVariables t :hintLetBindings t :hintFunctionParams t)))
                ))

(use-package! pinentry
  :init (setq epg-pinentry-mode `loopback)
  (pinentry-start))

(after! gptel
  (gptel-make-anthropic "Claude"          ;Any name you want
    :stream t                             ;Streaming responses
    :key (password-store-get "claude-api-key"))
  (setq
   ;; gptel-model 'claude-3-sonnet-20240229 ;  "claude-3-opus-20240229" also available
   gptel-model 'claude-sonnet-4-20250514
   gptel-backend (gptel-make-anthropic "Claude"
                   :stream t :key (password-store-get "claude-api-key")))
  )
